spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/civicConnect}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:laptop}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=94f83b1a8c9e5e3d7a2b9f6c4d1e8b7a4c5d2e1f9a8b7c6d5e4f3a2b1c0d9e8f
jwt.expiration=86400000

upload.dir=uploads
